import type { AudioSource, PomodoroSettings, TimerState } from '@/types/domain';
import { buildTimerForPhase } from '@/lib/pomodoro';

export const defaultSettings: PomodoroSettings = {
  workMinutes: 25,
  shortBreakMinutes: 5,
  longBreakMinutes: 15,
  longBreakInterval: 4,
  autoStartBreaks: true,
  autoStartPomodoros: false,
  dailyGoalSessions: 8,
  soundEnabled: true,
  notificationPermission:
    typeof Notification === 'undefined' ? 'unsupported' : Notification.permission,
  defaultAudioSourceId: null,
  ambientVolume: 0.45,
  ambientMuted: false,
};

export function createDefaultTimerState(settings: PomodoroSettings): TimerState {
  return buildTimerForPhase('work', settings);
}

export const builtInAudioSources: AudioSource[] = [
  {
    id: 'focus-chime',
    label: 'Focus chime',
    provider: 'system',
    kind: 'notification_sound',
    launchUrl: null,
    streamUrl: null,
    embedUrl: null,
    stationKey: 'focus',
    capabilities: {
      canPlayInline: false,
      canEmbed: false,
      canLaunch: false,
    },
    isFavorite: false,
    builtIn: true,
    description: 'Generated locally when a new focus block begins.',
  },
  {
    id: 'break-chime',
    label: 'Break chime',
    provider: 'system',
    kind: 'notification_sound',
    launchUrl: null,
    streamUrl: null,
    embedUrl: null,
    stationKey: 'break',
    capabilities: {
      canPlayInline: false,
      canEmbed: false,
      canLaunch: false,
    },
    isFavorite: false,
    builtIn: true,
    description: 'Generated locally when it is time to step away.',
  },
  {
    id: 'ambient-rain',
    label: 'Rain',
    provider: 'system',
    kind: 'direct_stream',
    launchUrl: null,
    streamUrl: '/ambient/rain.mp3',
    embedUrl: null,
    stationKey: 'ambient',
    capabilities: {
      canPlayInline: true,
      canEmbed: false,
      canLaunch: false,
    },
    isFavorite: false,
    builtIn: true,
    description: 'Steady rainfall on leaves.',
  },
  {
    id: 'ambient-waterfall',
    label: 'Waterfall',
    provider: 'system',
    kind: 'direct_stream',
    launchUrl: null,
    streamUrl: '/ambient/waterfall.mp3',
    embedUrl: null,
    stationKey: 'ambient',
    capabilities: {
      canPlayInline: true,
      canEmbed: false,
      canLaunch: false,
    },
    isFavorite: false,
    builtIn: true,
    description: 'Soft waterfall flow in the distance.',
  },
  {
    id: 'ambient-ocean',
    label: 'Ocean',
    provider: 'system',
    kind: 'direct_stream',
    launchUrl: null,
    streamUrl: '/ambient/ocean.mp3',
    embedUrl: null,
    stationKey: 'ambient',
    capabilities: {
      canPlayInline: true,
      canEmbed: false,
      canLaunch: false,
    },
    isFavorite: false,
    builtIn: true,
    description: 'Rolling waves with gentle surf noise.',
  },
  {
    id: 'ambient-forest',
    label: 'Forest',
    provider: 'system',
    kind: 'direct_stream',
    launchUrl: null,
    streamUrl: '/ambient/forest.mp3',
    embedUrl: null,
    stationKey: 'ambient',
    capabilities: {
      canPlayInline: true,
      canEmbed: false,
      canLaunch: false,
    },
    isFavorite: false,
    builtIn: true,
    description: 'Forest air with birds and wind.',
  },
  {
    id: 'ambient-fireplace',
    label: 'Fireplace',
    provider: 'system',
    kind: 'direct_stream',
    launchUrl: null,
    streamUrl: '/ambient/fireplace.mp3',
    embedUrl: null,
    stationKey: 'ambient',
    capabilities: {
      canPlayInline: true,
      canEmbed: false,
      canLaunch: false,
    },
    isFavorite: false,
    builtIn: true,
    description: 'Crackling fire for warm background texture.',
  },
  {
    id: 'ambient-brown-noise',
    label: 'Brown noise',
    provider: 'system',
    kind: 'direct_stream',
    launchUrl: null,
    streamUrl: '/ambient/brown-noise.mp3',
    embedUrl: null,
    stationKey: 'ambient',
    capabilities: {
      canPlayInline: true,
      canEmbed: false,
      canLaunch: false,
    },
    isFavorite: false,
    builtIn: true,
    description: 'Low-frequency brown noise for deep focus.',
  },
];
